config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  authenticate :admin do
    namespace :admins do
      root to: "sectors#index"
      resources :sectors, only: %i(index create show edit update destroy) do
        collection do
          patch :sort, to: 'sorts#update'
        end
        resources :sites, only: %i(index create show edit update destroy) do
          collection do
            patch :sort, to: 'sorts#update'
          end
        end
      end
      resources :addresses, only: %i(index) do
        collection do
          patch :sort, to: 'sorts#update'
        end
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/address.rb
class Address < ApplicationRecord

  # Config =====================================================================
  acts_as_list
  geocoded_by :address

  # Callbacks ==================================================================

  after_validation :geocode

  # Associations ===============================================================

  belongs_to :site
  belongs_to :sector

  # Validations ================================================================

  validates :street, :postal_code, :city, :sector_id, presence: true

  def address
    [street, postal_code, city].compact.join(', ')
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :registerable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sector.rb
class Sector < ApplicationRecord

  # Config =====================================================================

  acts_as_list

  # Associations ===============================================================
  has_many :addresses, dependent: :destroy
  has_many :sites, through: :addresses
  has_rich_text :description
  has_one_attached :illustration

  # Validations ================================================================

  validates :name, :illustration, :description, :city, presence: true
  validates :illustration, attached: true, content_type: [:png, :jpg, :jpeg]

end

app/models/site.rb
class Site < ApplicationRecord

  # Config =====================================================================
  acts_as_list
  enum category: %i[restaurant bar shop hiking]

  # Associations ===============================================================

  has_many :addresses, dependent: :delete_all
  has_many :sectors, through: :addresses
  accepts_nested_attributes_for :addresses, allow_destroy: true, reject_if: :all_blank
  has_rich_text :description
  has_one_attached :picture

  # Validations ================================================================

  validates :title, :opening_time, :description, :phone_number, :category, :picture, presence: true

end

app/controllers/admins/addresses_controller.rb
module Admins
  class AddressesController < ApplicationController

    def index
      @addresses = Address.all
    end

    def create
    end
  end
end

app/controllers/admins/sectors_controller.rb
module Admins
  class SectorsController < ApplicationController

    before_action :set_sector, only: [:show, :edit, :update, :destroy]

    def index
      @sector = Sector.new
      @q = Sector.ransack(params[:q])
      @sectors = @q.result(distinct: true).order(:position)
    end

    def create
      @sector = Sector.new(params_sector)
      if @sector.save
        respond_to do |format|
          format.html { redirect_to admins_root_path, notice: t('activerecord.attributes.sector.create.success') }
          format.js
        end
      else
        respond_to do |format|
          format.html { render "/admins" }
          format.js
        end
      end
    end

    def edit
    end

    def update
      if @sector.update(params_sector)
        redirect_to admins_root_path, notice: t('activerecord.attributes.sector.update.success')
      else
        render :edit
      end
    end

    def show
      @sites = @sector.sites
      @site = Site.new
      @site.addresses.build
    end

    def destroy
      if @sector.destroy
        respond_to do |format|
          format.html { redirect_to admins_root_path, notice: "Quartier supprimé avec succès" }
          format.js
        end
      else
        respond_to do |format|
          format.html { redirect_to admins_root_path, notice: "Echec de suppression, veuillez rééssayer" }
          format.js
        end
      end
    end

    private

    def set_sector
      @sector = Sector.find(params[:id])
    end

    def params_sector
      params.require(:sector).permit(
        :name,
        :illustration,
        :description,
        :city,
        :position
      )
    end

  end
end

app/controllers/admins/sites_controller.rb
module Admins

  class SitesController < ApplicationController

    before_action :set_sector, only: %i(create show edit update destroy)
    before_action :set_site, only: %i(show edit update destroy)

    def create
      @sector = Sector.find(params[:sector_id])
      @site = Site.new(params_site)
      if @site.save
        redirect_to admins_sector_url(@sector), notice: "Nouvelle adresse crée avec succès"
      else
        set_render_view
        @site.addresses.build
        render "admins/sectors/show"
      end
    end

    def show
    end

    def edit
    end

    def update
      if @site.update(params_site)
        redirect_to admins_sector_site_path(@sector, @site)
      else
        render :edit
      end
    end

    def destroy
      if @site.destroy
        redirect_to admins_sector_path(@sector), notice: "Addresse supprimée avec succès"
      else
        set_render_view
        @site.build_address
        render "admins/sectors/show", status: :unprocessable_entity
      end
    end

    private

    def set_sector
      @sector = Sector.find(params[:sector_id])
    end

    def set_site
      @site = Site.find(params[:id])
    end

    def set_render_view
      @sites = @sector.sites
      @site = Site.new
    end

    def params_site
      params.require(:site).permit(
        :title,
        :opening_time,
        :description,
        :phone_number,
        :website,
        :category,
        :picture,
        :position,
        addresses_attributes: [
          :street,
          :city,
          :postal_code,
          :sector_id
          ]
        )
    end
  end
end

app/controllers/admins/sorts_controller.rb
module Admins
  class SortsController < ApplicationController

    def update
      # take the new position for each record and update them in db
      params[object].each_with_index do |id, index|
        klass.where(id: id).update_all(position: index + 1)
      end

      head :ok
    end

    private

    def key_params
      request.parameters.keys[0]
    end

    def klass
      key_params.camelize.constantize
    end

    def object
      key_params.to_sym
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery :with_exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admins/addresses/_card.html.erb
<li class="item" data-site-id="<%= address.id %>" id="<%= dom_id(address)%>">
  <div class="card" style="width: 18rem;">
    <%= image_tag(address.site.picture, class: "image card-img-top") %>
    <div class="card-body">
      <h5 class="card-title"><%= address.site.title %></h5>
      <p class="card-text"><%= address.site.description %></p>
      <%= link_to "Voir", admins_sector_site_path(address.sector, address.site), class: "btn btn-primary" %>
    </div>
  </div>
</li>

app/views/admins/addresses/index.html.erb
<h1>Adresses à visiter Absolument</h1>

<%= link_to "retour", admins_root_path %>

<div class= "card-list sortable" data-url="<%= sort_admins_addresses_path %>">
  <% @addresses.each do |address| %>
    <%= render 'card', address: address %>
  <% end %>
</div>

app/views/admins/dashboards/_sector.html.erb
<tr data-sector-id="<%= sector.id %>">
  <td><%= sector.position %></td>
  <td><%= sector.name %></td>
  <td><%= sector.city %></td>
  <td>
    <%= link_to "Supprimer", admins_sector_path(sector), method: :delete, class: "button_delete", remote: true %>
  </td>
</tr>

app/views/admins/dashboards/index.html.erb
<div class="row">
  <h1>Bienvenue dans vos espace</h1>
</div>

<div class="row">
  <h2>Ajouter un quartier</h2>
</div>

<div class="row main">
  <div  id="sector">
    <%= render 'form' %>
  </div>

  <div>
    <table id="sector_list" class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Position</th>
          <th scope="col">Nom</th>
          <th scope="col">Ville</th>
          <th scope="col"></th>
        </tr>
      </thead>

      <tbody id="sectors">
        <% @sectors.each do |sector| %>
            <%= render "sector", sector: sector %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/sectors/_form.html.erb
  <%= form_with model: [:admins, @sector], data: { controller: "sectors" }  do |f| %>

    <div id="error_messages">
      <%= render "admins/shared/form_errors_messages" %>
    </div>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, data: { target: "sectors.name" },  class: "form-control",  id: "name" %>
    <div >

    <div class="form-group">
      <%= f.label :description %>
      <%= f.rich_text_area :description, placeholder: '400 caractères max', data: { target: "sectors.description" }, id: "description", class: "form-control" %>
    </div>

    <div  class="form-group">
      <%= f.label :city%>
      <%= f.text_field :city, label: 'Ville', data: { target: "sectors.city" }, class: "form-control", id: "city" %>
    </div>

    <div class="form-group">
      <%= f.label :illustration%>
      <%= f.file_field :illustration, id: "illustration", data: { target: "sectors.illustration" }%>
    </div>

     <%= f.button :submit, class: "button btn btn-primary", data: { action: "click->sectors#onSubmitSectorForm"} %>
  <% end %>

<br><br>

app/views/admins/sectors/_form_attributes.html.erb
    <div id="error_messages">
      <%= render "admins/shared/form_errors_messages", errors: @sector.errors %>
    </div>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, data: { target: "sectors.name" },  class: "form-control",  id: "name" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.rich_text_area :description, placeholder: '400 caractères max', data: { target: "sectors.description" }, id: "description", class: "form-control" %>
    </div>

    <div  class="form-group">
      <%= f.label :city%>
      <%= f.text_field :city, label: 'Ville', data: { target: "sectors.city" }, class: "form-control", id: "city" %>
    </div>

    <div class="form-group">
      <%= f.label :illustration%>
      <%= f.file_field :illustration, id: "illustration", data: { target: "sectors.illustration" }%>
    </div>

     <%= f.button "Enregistrer", class: "button btn btn-primary", data: { action: "click->sectors#onSubmitSectorForm"} %>

app/views/admins/sectors/_search_form.html.erb
<%= search_form_for [:admins, @q], html: { class: "form-inline "} do |f| %>
 <!-- Search if the name field contains... -->
  <div>
    <%= f.label :name_cont %>
    <%= f.search_field :name_cont, class: "form-control" %>
  </div>
  <div>
    <%= f.label :city_cont %>
    <%= f.search_field :city_cont, class: "form-control" %>
  </div>

  <div>
    <%= f.submit "Rechercher", class: "btn btn-primary search-form-button" %>
  </div>

<% end %>

app/views/admins/sectors/_sector.html.erb
<li class="item" data-sector-id="<%= sector.id %>" id="<%= dom_id(sector)%>">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= sector.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= sector.city %></h6>
      <p class="card-text"><%= sector.description %> </p>
      <%= link_to "Supprimer", admins_sector_path(sector), method: :delete, remote: true, class: "card-link" %>
      <%= link_to "Voir", admins_sector_path(sector), class: "card-link" %>
      <%= link_to "Editer", edit_admins_sector_path(sector), class: "card-link" %>
    </div>
  </div>
</li>

app/views/admins/sectors/create.js.erb
<% if @sector.errors.any? %>

  function addErrorMessages(html) {
    document.querySelector(".button").blur();
    var element = document.getElementById('error_messages')
    element.innerHTML = ""
    element.insertAdjacentHTML('beforeend', html);
  }
    var error_messages = `<%= j render "admins/shared/form_errors_messages", errors: @sector.errors %>`;
    addErrorMessages(error_messages);

<% else %>

  function refreshForm() {
    document.getElementById("name").value = "";
    document.getElementById("city").value = "";
    document.getElementById("illustration").value = "";
    document.getElementById("description").value = "";
  }

  function addSector() {
    new_sector = `<%= j render "admins/sectors/sector", sector: @sector %> `;
    document.getElementById('sectors').insertAdjacentHTML('beforeend', new_sector)
    document.querySelector(".button").blur();
  }

  function refreshErrorMessages() {
    var element = document.getElementById('error_messages')
    element.innerHTML = "";
  }

  refreshErrorMessages();
  addSector();
  refreshForm();
<% end %>

app/views/admins/sectors/destroy.js.erb
document.querySelector("[data-sector-id='<%= @sector.id%>']").remove()

app/views/admins/sectors/edit.html.erb
<h1>Mettez à jour le quartier</h1>
<%= form_with model: [:admins, @sector], data: { controller: "sectors" }, local: true  do |f| %>
  <%= render 'form_attributes', f:f %>
<% end %>

app/views/admins/sectors/index.html.erb
<div class="card shadow-lg p-3 mb-5 bg-white rounded">
  <div class="card-body">
    <h3 class="card-title">Bienvenue dans vos espace d'administration</h3>
    <p class="card-text">Depuis votre interface vous pouvez ajouter des quartiers ainsi que les bonnes addresses associées</p>
    <p class="card-text"><small class="text-muted">Dernière mise à jour: <%= l(Time.zone.now - 5.minutes, format: :short) %> </small></p>
    <p><%= link_to "Lister toutes les adresses", admins_addresses_path %> </p>
  </div>
</div>

<div class="card-form">
  <div id="sector" class="shadow-lg p-3 mb-5 bg-white rounded">
    <h4>Ajouter un quartier</h4>
    <%= form_with model: [:admins, @sector], data: { controller: "sectors" }, class: "sector-form"  do |f| %>
      <%= render 'form_attributes', f:f %>
    <% end %>
    <br><br>
  </div>
  <div class="search-form shadow-lg p-3 mb-5 bg-white rounded" >
    <h4>Liste des différents quartiers</h4>
    <%= render 'search_form' %>

    <ul class="sortable card-list" data-url="<%= sort_admins_sectors_path %>" >
      <% @sectors.each do |sector| %>
        <%= render "sector", sector: sector %>
      <% end %>
    </ul>
  </div>
</div>

app/views/admins/sectors/show.html.erb
<div class="card shadow-lg p-3 mb-5 bg-white rounded">
  <div class="card-body">
    <h4 class="card-title">Quartier <%= @sector.name %></h4>
    <p class="card-text"><%= @sector.description %></p>
    <p class="card-text"><small class="text-muted"><%= @sector.city %></small></p>
    <p class="card-text"><%= link_to "retour", admins_root_path %></p>
  </div>
</div>

<div class="card-form shadow-sm shadow-lg p-3 mb-5 bg-white rounded">
  <div class="site-form">
    <h5>Ajouter une Adresse au Quartier</h5>
    <%= render "admins/sites/form" %>
  </div>

  <div>
    <h5>Liste des bonnes adresses du quartier</h5>
    <% if @sector.addresses.empty? %>
      <p>Vous n'avez pas encore ajouté de bonnes addresses à ce quartier</p>
    <% end %>
    <ul class="card-list sortable" data-url="<%= sort_admins_sector_sites_path(@sector) %>">
      <% @sites.each do |site| %>
        <%= render 'admins/sites/cards', sector: @sector, site: site %>
      <% end %>
    </ul>
  </div>

</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_form_errors_messages.html.erb
<% if errors.any? %>
<ul>
  <% errors.full_messages.each do |msg| %>
    <li>
      <div class="alert alert-danger" role="alert">
        <%= msg %>
      </div>
      </li>
  <% end %>
</ul>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(".sign_in"), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t(".sign_up"), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t(".forgot_your_password"), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t('.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav navlinks">
      <%= link_to "Accueil", admins_root_path, class: "nav-item nav-link active" %>
      <% if current_admin %>
        <%= link_to "Se déconnecter", destroy_admin_session_path, class: "nav-item nav-link", method: :delete %>
      <% else %>
        <%= link_to "Se connecter", new_admin_session_path, class: "nav-item nav-link" %>
      <% end %>

    </div>
  </div>
</nav>

app/views/admins/sites/_address_form.html.erb
<%= f.fields_for :addresses do |address_field| %>
  <div class="form-row">
    <div class="col-7">
      <%= address_field.text_field :street, placeholder: "Rue", class: "form-control" %>
    </div>
    <div class="col">
      <%= address_field.text_field :city, placeholder: "Ville", class: "form-control" %>
    </div>
    <div class="col">
      <%= address_field.text_field :postal_code, placeholder: "Code postal", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= address_field.hidden_field :sector_id, value: @sector.id %>
  </div >
<% end %>

app/views/admins/sites/_cards.html.erb
<li class="item" data-site-id="<%= site.id %>" id="<%= dom_id(site)%>">
  <div class="card" style="width: 18rem;">
    <%= image_tag(site.picture, class: "image card-img-top") %>
    <div class="card-body">
      <h5 class="card-title"><%= site.title %></h5>
      <p class="card-text"><%= site.description %></p>
      <%= link_to "Voir", admins_sector_site_path(sector, site), class: "btn btn-primary" %>
    </div>
  </div>
</li>

app/views/admins/sites/_form.html.erb
<%= form_with model: [:admins, @sector, @site], local: true, class: "site-form" do |f| %>
  <div id="error_messages">
    <%= render "admins/shared/form_errors_messages", errors: @site.errors %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title,  class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :opening_time %>
    <%= f.time_field :opening_time,  class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.rich_text_area :description,  class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number,  class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :website %>
    <%= f.text_field :website,  class: "form-control" %>
  </div>

  <div class="col-auto my-1">
    <%= f.label :category, class: "mr-sm-2 sr-only", for: "inlineFormCustomSelect" %>
    <%= f.select :category, f.object.class.categories.collect { |k, _| [t("activerecord.attributes.site.category_name.#{k}"), k] }, class: "custom-select mr-sm-2", id: "inlineFormCustomSelect" %>
  </div>

  <%= render 'admins/sites/address_form', f:f %>

  <div class="form-group">
    <%= f.label :picture %>
    <%= f.file_field :picture  %>
  </div>

  <div>
    <%= f.button "Enregistrer",  class: "button btn btn-primary" %>
  </div>

<% end %>

app/views/admins/sites/edit.html.erb
<h1>Editer le site</h1>

<div><%= link_to "retour", admins_sector_path(@sector) %></div>

<%= render 'form' %>

app/views/admins/sites/show.html.erb
<h1>Informations sur l'addresse</h1>

<div><%= link_to "retour", admins_sector_path(@sector) %> </div>

<div><%= image_tag(@site.picture, class: "image") %></div>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">@site.title</h5>
    <h6 class="card-subtitle mb-2 text-muted">Horraire d'ouverture: <%= @site.opening_time %></h6>
    <h6 class="card-subtitle mb-2 text-muted">Numéro de téléphone: <%= @site.phone_number %></h6>
    <h6 class="card-subtitle mb-2 text-muted">Site internet: <%= @site.website %></h6>
    <h6 class="card-subtitle mb-2 text-muted">Category: <%= @site.category %></h6>
    <p class="card-text"><%= @site.description %></p>
    <%= link_to "Editer", edit_admins_sector_site_path(@sector, @site), class: "card-link" %>
    <%= link_to "Supprimer", admins_sector_site_path(@sector, @site), method: :delete, class: "card-link" %>
  </div>
</div>

app/views/admins/sites/update.html.erb
<h1>Sites#update</h1>
<p>Find me in app/views/sites/update.html.erb</p>

app/views/home/index.html.erb
<div class="container">
  <h1>Bienvenue sur votre guide touristique</h1>
  <p>Veuillez vous connecter sur le lien suivant pour accéder à l'application en tant qu'admin:</p>
  <a href="http://localhost:3000/admins">Accès au dashboard Admin</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TouristicGuide</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'admins/shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>